<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class BanksTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $banks = [
            [
                'type_id' => 1, // Commercial Bank Type (assuming ID 1)
                'category_id' => 1, // Commercial Banks Category (assuming ID 1)
                'name' => 'Kenya Commercial Bank',
                'trading_name' => 'KCB Group',
                'slug' => 'kenya-commercial-bank',
                'registration_number' => 'KCBB001',
                'tax_identification_number' => 'KCB123456789',
                'swift_code' => 'KCBLKENA',
                'routing_number' => '070000',
                'sort_code' => '11-00-00',
                'address_line_1' => 'KCB Centre',
                'address_line_2' => 'Kimathi Street',
                'city' => 'Nairobi',
                'country' => 'Kenya',
                'phone_number' => '+254-20-2220000',
                'email' => 'info@kcbgroup.com',
                'website' => 'https://www.kcbgroup.com',
                'founded_date' => '1896-01-01',
                'is_online_banking_available' => true,
                'is_mobile_banking_available' => true,
                'is_foreign_owned' => false,
                'is_government_owned' => false,
                'currency' => 'KES',
                'description' => 'Largest commercial bank in Kenya by assets',
                'is_active' => true,
                'is_featured' => true,
                '_status' => 1, // Active
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'type_id' => 1,
                'category_id' => 1,
                'name' => 'Equity Bank Kenya',
                'trading_name' => 'Equity Group',
                'slug' => 'equity-bank-kenya',
                'registration_number' => 'EQBK001',
                'tax_identification_number' => 'EQB987654321',
                'swift_code' => 'EQBLKENA',
                'routing_number' => '070001',
                'sort_code' => '12-00-00',
                'address_line_1' => 'Equity Centre',
                'address_line_2' => 'Upper Hill',
                'city' => 'Nairobi',
                'country' => 'Kenya',
                'phone_number' => '+254-20-2730000',
                'email' => 'info@equitygroup.com',
                'website' => 'https://www.equitygroup.com',
                'founded_date' => '1984-01-01',
                'is_online_banking_available' => true,
                'is_mobile_banking_available' => true,
                'is_foreign_owned' => false,
                'is_government_owned' => false,
                'currency' => 'KES',
                'description' => 'Leading bank with focus on SME and personal banking',
                'is_active' => true,
                'is_featured' => true,
                '_status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'type_id' => 2,
                'category_id' => 2,
                'name' => 'Kenya Women Microfinance Bank',
                'trading_name' => 'KWFT',
                'slug' => 'kenya-women-microfinance-bank',
                'registration_number' => 'KWMB001',
                'tax_identification_number' => 'KWM456789123',
                'swift_code' => 'KWFTKENA',
                'routing_number' => '070002',
                'sort_code' => '13-00-00',
                'address_line_1' => 'KWFT Headquarters',
                'address_line_2' => 'Mombasa Road',
                'city' => 'Nairobi',
                'country' => 'Kenya',
                'phone_number' => '+254-20-6950000',
                'email' => 'info@kwft.co.ke',
                'website' => 'https://www.kwft.co.ke',
                'founded_date' => '2008-01-01',
                'is_online_banking_available' => true,
                'is_mobile_banking_available' => true,
                'is_foreign_owned' => false,
                'is_government_owned' => false,
                'currency' => 'KES',
                'description' => 'Microfinance bank focused on women empowerment',
                'is_active' => true,
                'is_featured' => false,
                '_status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'type_id' => 3,
                'category_id' => 3,
                'name' => 'Industrial and Commercial Development Corporation',
                'trading_name' => 'ICDC',
                'slug' => 'industrial-commercial-development-corporation',
                'registration_number' => 'ICDC001',
                'tax_identification_number' => 'ICD789123456',
                'swift_code' => 'ICDCKENA',
                'routing_number' => '070003',
                'sort_code' => '14-00-00',
                'address_line_1' => 'ICDC House',
                'address_line_2' => 'Wabera Street',
                'city' => 'Nairobi',
                'country' => 'Kenya',
                'phone_number' => '+254-20-2221000',
                'email' => 'info@icdc.co.ke',
                'website' => 'https://www.icdc.co.ke',
                'founded_date' => '1954-01-01',
                'is_online_banking_available' => false,
                'is_mobile_banking_available' => false,
                'is_foreign_owned' => false,
                'is_government_owned' => true,
                'currency' => 'KES',
                'description' => 'Government development finance institution',
                'is_active' => true,
                'is_featured' => false,
                '_status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'type_id' => 5,
                'category_id' => 5,
                'name' => 'Gulf African Bank',
                'trading_name' => 'GAB',
                'slug' => 'gulf-african-bank',
                'registration_number' => 'GABK001',
                'tax_identification_number' => 'GAB321654987',
                'swift_code' => 'GULFKENA',
                'routing_number' => '070004',
                'sort_code' => '15-00-00',
                'address_line_1' => 'GAB Centre',
                'address_line_2' => 'Riverside Drive',
                'city' => 'Nairobi',
                'country' => 'Kenya',
                'phone_number' => '+254-20-2860000',
                'email' => 'info@gulfafricanbank.com',
                'website' => 'https://www.gulfafricanbank.com',
                'founded_date' => '2007-01-01',
                'is_online_banking_available' => true,
                'is_mobile_banking_available' => true,
                'is_foreign_owned' => false,
                'is_government_owned' => false,
                'currency' => 'KES',
                'description' => 'First fully Sharia-compliant bank in Kenya',
                'is_active' => true,
                'is_featured' => false,
                '_status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        foreach ($banks as $bank) {
            $bank['uuid'] = Str::uuid();
            DB::table('banks')->insert($bank);
        }
    }
}
