<?php

namespace Database\Seeders;

use Illuminate\Support\Str;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Sample countries data
        // Only countries in Eastern and Central Africa, with all columns from the schema
        $countries = [
            [
                'name' => 'Kenya',
                'uuid' => (string) Str::uuid(),
                'slug' => Str::slug('Kenya'),
                'demonym' => 'Kenyan',
                'description' => 'An East African country known for its wildlife safaris and Great Rift Valley.',
                'notes' => null,
                'sort_order' => 1,
                'iso_code' => 'KE',
                'iso3_code' => 'KEN',
                'numeric_code' => '404',
                'tld' => '.ke',
                'currency_code' => 'KES',
                'currency_name' => 'Kenyan Shilling',
                'currency_symbol' => 'KSh',
                'currency_rate' => 1.00,
                'capital_city' => 'Nairobi',
                'region' => 'Africa',
                'subregion' => 'East Africa',
                'latitude' => -1.2921,
                'longitude' => 36.8219,
                'area' => 580367.00,
                'population' => 53771300,
                'government_type' => 0,
                'driving_side' => 0,
                'phone_code' => '+254',
                'zip_code_format' => null,
                'languages' => json_encode(['en', 'sw']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Uganda',
                'uuid' => (string) Str::uuid(),
                'slug' => Str::slug('Uganda'),
                'demonym' => 'Ugandan',
                'description' => 'A country in East Africa known for its mountains and wildlife.',
                'notes' => null,
                'sort_order' => 2,
                'iso_code' => 'UG',
                'iso3_code' => 'UGA',
                'numeric_code' => '800',
                'tld' => '.ug',
                'currency_code' => 'UGX',
                'currency_name' => 'Ugandan Shilling',
                'currency_symbol' => 'USh',
                'currency_rate' => 3700.00,
                'capital_city' => 'Kampala',
                'region' => 'Africa',
                'subregion' => 'East Africa',
                'latitude' => 0.3476,
                'longitude' => 32.5825,
                'area' => 241038.00,
                'population' => 45741000,
                'government_type' => 0,
                'driving_side' => 0,
                'phone_code' => '+256',
                'zip_code_format' => null,
                'languages' => json_encode(['en', 'sw']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Tanzania',
                'uuid' => (string) Str::uuid(),
                'slug' => Str::slug('Tanzania'),
                'demonym' => 'Tanzanian',
                'description' => 'A country in East Africa known for Serengeti National Park and Mount Kilimanjaro.',
                'notes' => null,
                'sort_order' => 3,
                'iso_code' => 'TZ',
                'iso3_code' => 'TZA',
                'numeric_code' => '834',
                'tld' => '.tz',
                'currency_code' => 'TZS',
                'currency_name' => 'Tanzanian Shilling',
                'currency_symbol' => 'TSh',
                'currency_rate' => 2500.00,
                'capital_city' => 'Dodoma',
                'region' => 'Africa',
                'subregion' => 'East Africa',
                'latitude' => -6.1630,
                'longitude' => 35.7516,
                'area' => 945087.00,
                'population' => 59734000,
                'government_type' => 0,
                'driving_side' => 0,
                'phone_code' => '+255',
                'zip_code_format' => null,
                'languages' => json_encode(['sw', 'en']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Rwanda',
                'uuid' => (string) Str::uuid(),
                'slug' => Str::slug('Rwanda'),
                'demonym' => 'Rwandan',
                'description' => 'A landlocked East African country known for its wildlife and hills.',
                'notes' => null,
                'sort_order' => 4,
                'iso_code' => 'RW',
                'iso3_code' => 'RWA',
                'numeric_code' => '646',
                'tld' => '.rw',
                'currency_code' => 'RWF',
                'currency_name' => 'Rwandan Franc',
                'currency_symbol' => 'FRw',
                'currency_rate' => 1200.00,
                'capital_city' => 'Kigali',
                'region' => 'Africa',
                'subregion' => 'East Africa',
                'latitude' => -1.9706,
                'longitude' => 30.1044,
                'area' => 26338.00,
                'population' => 12952218,
                'government_type' => 0,
                'driving_side' => 0,
                'phone_code' => '+250',
                'zip_code_format' => null,
                'languages' => json_encode(['rw', 'en', 'fr']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Burundi',
                'uuid' => (string) Str::uuid(),
                'slug' => Str::slug('Burundi'),
                'demonym' => 'Burundian',
                'description' => 'A landlocked country in East Africa known for its hills and lakes.',
                'notes' => null,
                'sort_order' => 5,
                'iso_code' => 'BI',
                'iso3_code' => 'BDI',
                'numeric_code' => '108',
                'tld' => '.bi',
                'currency_code' => 'BIF',
                'currency_name' => 'Burundian Franc',
                'currency_symbol' => 'FBu',
                'currency_rate' => 2000.00,
                'capital_city' => 'Gitega',
                'region' => 'Africa',
                'subregion' => 'East Africa',
                'latitude' => -3.4264,
                'longitude' => 29.9306,
                'area' => 27834.00,
                'population' => 11890784,
                'government_type' => 0,
                'driving_side' => 0,
                'phone_code' => '+257',
                'zip_code_format' => null,
                'languages' => json_encode(['rn', 'fr']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'South Sudan',
                'uuid' => (string) Str::uuid(),
                'slug' => Str::slug('South Sudan'),
                'demonym' => 'South Sudanese',
                'description' => 'A landlocked country in East-Central Africa known for its civil war history.',
                'notes' => null,
                'sort_order' => 6,
                'iso_code' => 'SS',
                'iso3_code' => 'SSD',
                'numeric_code' => '728',
                'tld' => '.ss',
                'currency_code' => 'SSP',
                'currency_name' => 'South Sudanese Pound',
                'currency_symbol' => 'SS£',
                'currency_rate' => 650.00,
                'capital_city' => 'Juba',
                'region' => 'Africa',
                'subregion' => 'Central Africa',
                'latitude' => 4.8594,
                'longitude' => 31.5713,
                'area' => 619745.00,
                'population' => 11193725,
                'government_type' => 0,
                'driving_side' => 1,
                'phone_code' => '+211',
                'zip_code_format' => null,
                'languages' => json_encode(['en']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Democratic Republic of the Congo',
                'uuid' => (string) Str::uuid(),
                'slug' => Str::slug('Democratic Republic of the Congo'),
                'demonym' => 'Congolese',
                'description' => 'A country in Central Africa known for its vast rainforests and Congo River.',
                'notes' => null,
                'sort_order' => 7,
                'iso_code' => 'CD',
                'iso3_code' => 'COD',
                'numeric_code' => '180',
                'tld' => '.cd',
                'currency_code' => 'CDF',
                'currency_name' => 'Congolese Franc',
                'currency_symbol' => 'FC',
                'currency_rate' => 2000.00,
                'capital_city' => 'Kinshasa',
                'region' => 'Africa',
                'subregion' => 'Central Africa',
                'latitude' => -4.4419,
                'longitude' => 15.2663,
                'area' => 2344858.00,
                'population' => 89561403,
                'government_type' => 0,
                'driving_side' => 1,
                'phone_code' => '+243',
                'zip_code_format' => null,
                'languages' => json_encode(['fr', 'ln', 'kg', 'sw', 'lu']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Republic of the Congo',
                'uuid' => (string) Str::uuid(),
                'slug' => Str::slug('Republic of the Congo'),
                'demonym' => 'Congolese',
                'description' => 'A country in Central Africa known for its rainforests and Atlantic coastline.',
                'notes' => null,
                'sort_order' => 8,
                'iso_code' => 'CG',
                'iso3_code' => 'COG',
                'numeric_code' => '178',
                'tld' => '.cg',
                'currency_code' => 'XAF',
                'currency_name' => 'Central African CFA franc',
                'currency_symbol' => 'FCFA',
                'currency_rate' => 655.96,
                'capital_city' => 'Brazzaville',
                'region' => 'Africa',
                'subregion' => 'Central Africa',
                'latitude' => -4.2634,
                'longitude' => 15.2429,
                'area' => 342000.00,
                'population' => 5518087,
                'government_type' => 0,
                'driving_side' => 1,
                'phone_code' => '+242',
                'zip_code_format' => null,
                'languages' => json_encode(['fr', 'kg', 'ln']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Cameroon',
                'uuid' => (string) Str::uuid(),
                'slug' => Str::slug('Cameroon'),
                'demonym' => 'Cameroonian',
                'description' => 'A country in Central Africa known for its diverse geography and wildlife.',
                'notes' => null,
                'sort_order' => 9,
                'iso_code' => 'CM',
                'iso3_code' => 'CMR',
                'numeric_code' => '120',
                'tld' => '.cm',
                'currency_code' => 'XAF',
                'currency_name' => 'Central African CFA franc',
                'currency_symbol' => 'FCFA',
                'currency_rate' => 655.96,
                'capital_city' => 'Yaoundé',
                'region' => 'Africa',
                'subregion' => 'Central Africa',
                'latitude' => 3.8480,
                'longitude' => 11.5021,
                'area' => 475442.00,
                'population' => 26545863,
                'government_type' => 0,
                'driving_side' => 1,
                'phone_code' => '+237',
                'zip_code_format' => null,
                'languages' => json_encode(['fr', 'en']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Chad',
                'uuid' => (string) Str::uuid(),
                'slug' => Str::slug('Chad'),
                'demonym' => 'Chadian',
                'description' => 'A landlocked country in Central Africa known for its desert landscapes and Lake Chad.',
                'notes' => null,
                'sort_order' => 10,
                'iso_code' => 'TD',
                'iso3_code' => 'TCD',
                'numeric_code' => '148',
                'tld' => '.td',
                'currency_code' => 'XAF',
                'currency_name' => 'Central African CFA franc',
                'currency_symbol' => 'FCFA',
                'currency_rate' => 655.96,
                'capital_city' => 'N’Djamena',
                'region' => 'Africa',
                'subregion' => 'Central Africa',
                'latitude' => 12.1348,
                'longitude' => 15.0557,
                'area' => 1284000.00,
                'population' => 16425864,
                'government_type' => 0,
                'driving_side' => 1,
                'phone_code' => '+235',
                'zip_code_format' => null,
                'languages' => json_encode(['fr', 'ar']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Central African Republic',
                'uuid' => (string) Str::uuid(),
                'slug' => Str::slug('Central African Republic'),
                'demonym' => 'Central African',
                'description' => 'A landlocked country in Central Africa known for its wildlife and rainforests.',
                'notes' => null,
                'sort_order' => 11,
                'iso_code' => 'CF',
                'iso3_code' => 'CAF',
                'numeric_code' => '140',
                'tld' => '.cf',
                'currency_code' => 'XAF',
                'currency_name' => 'Central African CFA franc',
                'currency_symbol' => 'FCFA',
                'currency_rate' => 655.96,
                'capital_city' => 'Bangui',
                'region' => 'Africa',
                'subregion' => 'Central Africa',
                'latitude' => 4.3947,
                'longitude' => 18.5582,
                'area' => 622984.00,
                'population' => 4829767,
                'government_type' => 0,
                'driving_side' => 1,
                'phone_code' => '+236',
                'zip_code_format' => null,
                'languages' => json_encode(['fr', 'sg']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Djibouti',
                'uuid' => (string) Str::uuid(),
                'slug' => Str::slug('Djibouti'),
                'demonym' => 'Djiboutian',
                'description' => 'A small country in East Africa known for its strategic location near the Red Sea.',
                'notes' => null,
                'sort_order' => 12,
                'iso_code' => 'DJ',
                'iso3_code' => 'DJI',
                'numeric_code' => '262',
                'tld' => '.dj',
                'currency_code' => 'DJF',
                'currency_name' => 'Djiboutian franc',
                'currency_symbol' => 'Fdj',
                'currency_rate' => 177.72,
                'capital_city' => 'Djibouti',
                'region' => 'Africa',
                'subregion' => 'East Africa',
                'latitude' => 11.8251,
                'longitude' => 42.5903,
                'area' => 23200.00,
                'population' => 988000,
                'government_type' => 0,
                'driving_side' => 1,
                'phone_code' => '+253',
                'zip_code_format' => null,
                'languages' => json_encode(['fr', 'ar']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        // Insert countries into the database
        foreach ($countries as $country) {
            DB::table('countries')->insert([
                'uuid' => $country['uuid'],
                'name' => $country['name'],
                'slug' => $country['slug'],
                'demonym' => $country['demonym'],
                'description' => $country['description'],
                'notes' => $country['notes'],
                'sort_order' => $country['sort_order'],
                'iso_code' => $country['iso_code'],
                'iso3_code' => $country['iso3_code'],
                'numeric_code' => $country['numeric_code'],
                'tld' => $country['tld'],
                'currency_code' => $country['currency_code'],
                'currency_name' => $country['currency_name'],
                'currency_symbol' => $country['currency_symbol'],
                'currency_rate' => $country['currency_rate'],
                'capital_city' => $country['capital_city'],
                'region' => $country['region'],
                'subregion' => $country['subregion'],
                'latitude' => $country['latitude'],
                'longitude' => $country['longitude'],
                'area' => $country['area'],
                'population' => $country['population'],
                'government_type' => $country['government_type'],
                'driving_side' => $country['driving_side'],
                'phone_code' => $country['phone_code'],
                'zip_code_format' => $country['zip_code_format'],
                'languages' => $country['languages'],
                'created_at' => $country['created_at'],
                'updated_at' => $country['updated_at'],
            ]);
        }
    }
}